Update setup bootstrap into modular, idempotent scripts.
Add a zero-dependency installer and wrapper entrypoints while documenting one-line install and CLI usage for dry-run/sectioned execution.

Made-with: Cursor

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,274 +1,12 @@
-#! /bin/bash
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-NC='\033[0m' # No Color
-YELLOW='\033[0;93m'
+#!/usr/bin/env bash
+set -Eeuo pipefail
 
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-
-function die() {
-  printf "\n${RED}${@}${NC}\n"
+if [[ ! -x "${SCRIPT_DIR}/setup/bootstrap.sh" ]]; then
+  echo "Missing setup/bootstrap.sh" >&2
   exit 1
-}
+fi
 
-function donemsg() {
-  sleep 2
-  printf "${GREEN}DONE!${NC}\n"
-  sleep 1
-}
-
-function update_apt() {
-  printf "updating apt..."
-
-  # Start tailing the output in the background
-  tail -n 10 -f <(tee -a temp_output.txt)
-
-  {
-    sudo apt -y update
-  } >> temp_output.txt 2>&1
-
-  # Stop tailing the output
-  pkill -P $$ tail
-
-  donemsg
-}
-
-function install_prereqs() {
-  printf "installing prereqs..."
-
-  # Start tailing the output in the background
-  tail -n 10 -f <(tee -a temp_output.txt)
-
-  {
-    # Required for rbenv and ruby
-    sudo apt -y install autoconf bison build-essential libssl-dev libyaml-dev \
-      libreadline-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libpq-dev
-    # Required for vscode
-    sudo apt -y install apt-transport-https
-    # Required for docker
-    sudo apt -y install ca-certificates
-
-    # Required for capslock to esc key
-    # https://askubuntu.com/questions/1059663/remapping-caps-lock-to-escape-in-ubuntu-18-04-bionic
-    # sudo apt -y install gnome-tweak-tool
-    # Gnome Tweaks -> Keyboard & Mouse -> Additional Layout Options -> Caps Lock key behavior.
-
-    sudo apt -y install wget
-    sudo apt -y install vim
-    sudo apt -y install ack
-    sudo apt -y install gdebi
-  } >> temp_output.txt 2>&1
-
-  # Stop tailing the output
-  pkill -P $$ tail
-
-  donemsg
-}
-
-function install_zsh() {
-  printf "installing oh-my-zsh..."
-
-  # Start tailing the output in the background
-  tail -n 10 -f <(tee -a temp_output.txt)
-
-  {
-    sudo apt -y install zsh
-    sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
-  } >> temp_output.txt 2>&1
-
-  # Stop tailing the output
-  pkill -P $$ tail
-
-  chsh -s $(which zsh)
-  donemsg
-}
-
-function move_files() {
-  # move dotfiles
-  printf "moving dotfiles to hidden..."
-  mv $HOME/dotfiles ~/.dotfiles &> /dev/null
-  donemsg
-  printf "renaming old dirs to *.old if exist..."
-  sleep 1
-  {
-    for i in $HOME/.vim \
-      $HOME/.vimrc \
-      $HOME/.gvimrc \
-      $HOME/.gvimrc.before \
-      $HOME/.gvimrc.after \
-      $HOME/.vimrc.before \
-      $HOME/.vimrc.after \
-      $HOME/.gitignore_global \
-      $HOME/.zshrc \
-      $HOME/.config/Code/User/settings.json; do
-      if [[ ( -e $i ) || ( -h $i ) ]]; then
-        echo "${i} has been renamed to ${i}.old"
-        mv "${i}" "${i}.old" || die "Could not move ${i} to ${i}.old"
-      fi
-    done
-  } &> /dev/null
-  donemsg
-}
-
-function config_files() {
-  # Remove and replace .vimrc.before after files
-  printf "setting up configuration files..."
-  sleep 1
-  {
-    ln -s $HOME/.dotfiles/vim $HOME/.vim
-    ln -s $HOME/.dotfiles/vim/vimrc $HOME/.vimrc
-    ln -s $HOME/.dotfiles/vim/gvimrc $HOME/.gvimrc
-    ln -s $HOME/.dotfiles/vim/gvimrc.before $HOME/.gvimrc.before
-    ln -s $HOME/.dotfiles/vim/gvimrc.after $HOME/.gvimrc.after
-    ln -s $HOME/.dotfiles/vim/vimrc.before $HOME/.vimrc.before
-    ln -s $HOME/.dotfiles/vim/vimrc.after $HOME/.vimrc.after
-    ln -s $HOME/.dotfiles/git/gitignore_global $HOME/.gitignore_global
-    ln -s $HOME/.dotfiles/zsh/zshrc $HOME/.zshrc
-    ln -s $HOME/.dotfiles/zsh/custom/aliases.zsh $HOME/.oh-my-zsh/custom/aliases.zsh
-    ln -s $HOME/.dotfiles/zsh/custom/completions.zsh $HOME/.oh-my-zsh/custom/completions.zsh
-    ln -s $HOME/.dotfiles/zsh/custom/exports.zsh $HOME/.oh-my-zsh/custom/exports.zsh
-    # ln -s $HOME/.dotfiles/vscode/settings.json $HOME/.config/Code/User/settings.json
-    # ln -s $HOME/.dotfiles/vscode/settings.json /mnt/c/Users/$WINUSER}/AppData/Roaming/Code/User/settings.json
-    # ln -s $HOME/.dotfiles/wsl/wslconfig /mnt/c/Users/$WINUSER/.wslconfig
-  } &> /dev/null
-  donemsg
-}
-
-function install_node() {
-  printf "installing node and yarn..."
-
-  # Start tailing the output in the background
-  tail -n 10 -f <(tee -a temp_output.txt)
-
-  {
-    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&\
-    sudo apt-get install -y nodejs
-  } >> temp_output.txt 2>&1
-
-  # Stop tailing the output
-  pkill -P $$ tail
-  donemsg
-}
-
-function install_postgres() {
-  printf "installing other postgresql..."
-
-  # Start tailing the output in the background
-  tail -n 10 -f <(tee -a temp_output.txt)
-
-  {
-    # Install postgres
-    sudo apt -y install postgresql postgresql-contrib
-  } >> temp_output.txt 2>&1
-
-  # Stop tailing the output
-  pkill -P $$ tail
-  donemsg
-}
-
-function create_env() {
-  # setup dev env
-  printf "Creating code directories..."
-  sleep 2
-  {
-    mkdir -p $HOME/Code
-    mkdir -p $HOME/Code/github.com
-    mkdir -p $HOME/Code/github.com/nateleavitt
-    mkdir -p $HOME/Code/github.com/loyalstream
-    mkdir -p $HOME/.config/Code/User
-  } &> /dev/null
-  donemsg
-}
-
-function install_ruby() {
-  printf "installing rbenv..."
-
-  # Start tailing the output in the background
-  tail -n 10 -f <(tee -a temp_output.txt)
-
-  {
-    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
-    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshrc
-    echo 'eval "$(rbenv init -)"' >> ~/.zshrc
-    git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
-  } >> temp_output.txt 2>&1
-
-  # Stop tailing the output
-  pkill -P $$ tail
-  donemsg
-}
-
-function config_git() {
-  printf  "Configuring global git ignore..."
-  sleep 1
-  git config --global core.excludesfile ~/.gitignore_global &> /dev/null
-  donemsg
-}
-
-function install_vim_plugins() {
-  printf "downloading and configuring vim plugins..."
-  sleep 1
-  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim &> /dev/null
-  vim +PluginInstall +qall
-  donemsg
-}
-
-function install_gcloud() {
-  printf "installing gcloud..."
-
-  # Start tailing the output in the background
-  tail -n 10 -f <(tee -a temp_output.txt)
-
-  {
-    sudo apt -y install apt-transport-https ca-certificates gnupg curl sudo
-    echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
-    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
-    sudo apt update && sudo apt -y install google-cloud-cli
-    sudoe apt -y install google-cloud-sdk-gke-gcloud-auth-plugin
-  } >> temp_output.txt 2>&1
-
-  # Stop tailing the output
-  pkill -P $$ tail
-
-  donemsg
-}
-
-function remove_packages() {
-  printf "cleaning up and removing old packages..."
-  sleep 1
-  sudo apt -y autoremove &> /dev/null
-  donemsg
-}
-
-# INSTALL
-printf "\n"
-printf "*******************************************************\n"
-printf "${GREEN}Welcome to nateleavitt's Linux setup script${NC}\n"
-printf "*******************************************************\n"
-# sudo apt -y update 2>&1 | tee -a temp_output.txt | tail -n 10 -f
-update_apt
-install_prereqs
-install_zsh
-move_files
-config_files
-install_node
-install_postgres
-create_env
-install_ruby
-config_git
-install_vim_plugins
-install_gcloud
-remove_packages
-sleep 2
-printf "*******************************************************\n"
-printf "${GREEN}Everything is now setup!${NC}\n"
-# might want to output: https://github.com/Microsoft/vscode/issues/23991
-sleep 1
-printf "\n"
-printf "Let me know if you have any questions:\n"
-printf "https://github.com/nateleavitt/dotfiles\n"
-printf "${GREEN}Thank you!${NC}\n"
-printf "*******************************************************\n"
-printf "Note: run 'gcloud init' to initialize gcloud\n"
-printf "\n"
+exec "${SCRIPT_DIR}/setup/bootstrap.sh" "$@"
 
diff --git a/bootstrap-osx b/bootstrap-osx
--- a/bootstrap-osx
+++ b/bootstrap-osx
@@ -1,193 +1,17 @@
-#! /bin/bash
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-NC='\033[0m' # No Color
-YELLOW='\033[0;93m'
+#!/usr/bin/env bash
+set -Eeuo pipefail
 
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-
-function die() {
-  printf "\n${RED}${@}${NC}\n"
+if [[ "$(uname -s)" != "Darwin" ]]; then
+  echo "bootstrap-osx is for macOS only." >&2
   exit 1
-}
+fi
 
-function donemsg() {
-  sleep 2
-  printf "\e[93m${GREEN}DONE!${NC}\n"
-  sleep 1
-}
+if [[ ! -x "${SCRIPT_DIR}/setup/bootstrap.sh" ]]; then
+  echo "Missing setup/bootstrap.sh" >&2
+  exit 1
+fi
 
-function install_homebrew() {
-  printf "installing homebrew\n"
-  sleep 1
-  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-  donemsg
-}
-
-function install_ruby() {
-  printf "installing ruby\n"
-  sleep 1
-  brew install rbenv ruby-build
-  donemsg
-}
-
-function install_zsh() {
-  printf "installing oh-my-zsh\n"
-  sleep 1
-  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-  sleep 1
-  chsh -s /bin/zsh
-  donemsg
-}
-
-# TODO: Need to configure zsh
-
-function install_node() {
-  printf "installing node and yarn\n"
-  sleep 1
-  brew install node
-  donemsg
-}
-
-function install_vscode() {
-  printf "installing vscode\n"
-  sleep 1
-  brew install visual-studio-code --cask
-  donemsg
-}
-
-function install_docker() {
-  printf "installing docker\n"
-  sleep 1
-  brew install docker --cask
-  unset DOCKER_HOST
-  donemsg
-}
-
-function install_other() {
-  printf "installing other tools\n"
-  sleep 1
-  brew install typora --cask
-  brew install slack --cask
-  brew install ack
-  brew install wget
-  defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
-  defaults write dev.warp.Warp-Stable "ApplePressAndHoldEnabled" -bool false
-  defaults write com.apple.dock autohide-delay -float 0; killall Dock
-  donemsg
-}
-
-function create_env() {
-  # setup dev env
-  printf "Creating Developer directories\n"
-  sleep 1
-  mkdir $HOME/Developer
-  mkdir $HOME/Developer/github.com
-  mkdir $HOME/Developer/github.com/nateleavitt
-  mkdir $HOME/Developer/github.com/loyalstream
-  donemsg
-}
-
-function move_files() {
-  # move dotfiles
-  printf "moving dotfiles to hidden\n"
-  mv $HOME/dotfiles ~/.dotfiles
-  # Add <strong>.old</strong> to any existing Vim file in the home directory
-  sleep 1
-  printf "renaming old dirs to *.old if exist\n"
-  sleep 1
-  for i in $HOME/.vim \
-    $HOME/.vimrc \
-    $HOME/.gvimrc \
-    $HOME/.gvimrc.before \
-    $HOME/.gvimrc.after \
-    $HOME/.vimrc.before \
-    $HOME/.vimrc.after \
-    $HOME/.gitignore_global \
-    $HOME/.hyper.js \
-    $HOME/.zshrc \
-    $HOME/.oh-my-zsh/custom/aliases.zsh \
-    $HOME/.oh-my-zsh/custom/completions.zsh \
-    $HOME/.oh-my-zsh/custom/exports.zsh; do
-    # $HOME/Library/Application\ Support/Code/User/settings.json; do
-    if [[ ( -e $i ) || ( -h $i ) ]]; then
-      echo "${i} has been renamed to ${i}.old"
-      mv "${i}" "${i}.old" || die "Could not move ${i} to ${i}.old"
-    fi
-  done
-  donemsg
-}
-
-function config_files() {
-  # Remove and replace .vimrc.before after files
-  printf "setting up vim and configuring git\n"
-  sleep 1
-  ln -s $HOME/.dotfiles/vim $HOME/.vim
-  ln -s $HOME/.dotfiles/vim/vimrc $HOME/.vimrc
-  ln -s $HOME/.dotfiles/vim/gvimrc $HOME/.gvimrc
-  ln -s $HOME/.dotfiles/vim/gvimrc.before $HOME/.gvimrc.before
-  ln -s $HOME/.dotfiles/vim/gvimrc.after $HOME/.gvimrc.after
-  ln -s $HOME/.dotfiles/vim/vimrc.before $HOME/.vimrc.before
-  ln -s $HOME/.dotfiles/vim/vimrc.after $HOME/.vimrc.after
-  ln -s $HOME/.dotfiles/git/gitignore_global $HOME/.gitignore_global
-  ln -s $HOME/.dotfiles/zsh/zshrc $HOME/.zshrc
-  ln -s $HOME/.dotfiles/zsh/custom/aliases.zsh $HOME/.oh-my-zsh/custom/aliases.zsh
-  ln -s $HOME/.dotfiles/zsh/custom/completions.zsh $HOME/.oh-my-zsh/custom/completions.zsh
-  ln -s $HOME/.dotfiles/zsh/custom/exports.zsh $HOME/.oh-my-zsh/custom/exports.zsh
-  # ln -s $HOME/.dotfiles/vscode/settings.json $HOME/Library/Application\ Support/Code/User/
-  donemsg
-}
-
-function config_git() {
-  printf  "Configuring global git ignore\n"
-  sleep 1
-  git config --global core.excludesfile ~/.gitignore_global
-  # git config --global credential.helper osxkeychain
-  git config --global pager.branch false
-  donemsg
-}
-
-function install_vim_plugins() {
-  printf "downloading and configuring vim plugins\n"
-  sleep 1
-  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
-  vim +PluginInstall +qall
-  donemsg
-}
-
-function install_font() {
-  printf "installing SF Mono font\n"
-  sleep 1
-  cp font/*.otf $HOME/Library/Fonts/
-  domemsg
-}
-
-# INSTALL
-printf "\n"
-printf "*******************************************************\n"
-printf "${GREEN}Welcome to nateleavitt's OSX setup script${NC}\n"
-printf "*******************************************************\n"
-sleep 3
-# install_homebrew
-move_files
-config_files
-install_ruby
-install_zsh
-install_node
-install_vscode
-# install_docker
-install_other
-create_env
-config_git
-install_vim_plugins
-sleep 2
-printf "*******************************************************\n"
-printf "${GREEN}Everything is now setup!${NC}\n"
-sleep 2
-printf "\n"
-printf "Let me know if you have any questions:\n"
-printf "https://github.com/nateleavitt/dotfiles\n"
-printf "e[93 ${GREEN}Thank you!${NC}\n"
-printf "*******************************************************\n"
-printf "\n"
+exec "${SCRIPT_DIR}/setup/bootstrap.sh" "$@"
 
